### ISSUE TITLE
Signed Transactions Do Not Work With Hiro's API

### ISSUE THREAD

**Issue by linden** [valeralabs/sdk#16]
currently when submitting [our signed example transaction](https://github.com/valeralabs/sdk/blob/2dc6f5b7fe12750eb43311331de6849b3cea3139/transaction/transaction_test.go#L126) to [Hiro's api](https://hirosystems.github.io/stacks-blockchain-api/#tag/Transactions/operation/post_core_node_transactions), I get the following error.
```sh
curl "https://stacks-node-api.mainnet.stacks.co/v2/transactions" -X POST -H "content-type: application/octet-stream" --data-raw "0000000001040015c31b8c1c11c515e244b75806bac48d1399c775000000000000000a0000000000000001000135230d6a06749377212758f925871c1106fb258abed738df874a858f6f394881786d413dccfe8b134f0a8f820ce72220b8201b1cfc43ac365cf1e23f4f4003ab030200000000000516f5f1d7c482c6e1f8330b4805c5c03d8409d32452000000000000006468656c6c6f0000000000000000000000000000000000000000000000000000000000"
> "Failed to deserialize posted transaction: Failed to parse transaction authorization: unrecognized auth flags 48"
```
while this transaction should fail since it's from a random account with 0 STX, this looks like a parsing error.
I've done a bit of investigating and it's something to do with [this](https://github.com/stacks-network/stacks-blockchain/blob/26bfd5fcdc1f25106288f18ced05290b569f6abb/src/chainstate/stacks/auth.rs#L872).

**Comment by mooseman1241** [comment]
I've found the issue. Currently we're sending hex encoded data the API, but the API isn't expecting the transaction data to be encoded. I've tested with ExampleTokenTransfer, and I got the response:
```
{"error":"transaction rejected","reason":"FeeTooLow","reason_data":{"actual":1,"expected":180},"txid":"5f4a2b0f9890d7d46d6f40cb2111e76b2ab6bde4c02d6cc0e210a1d8e9ccfd1d"}%
```
Well it still returns an error, its not a parsing error.

**Comment by linden** [comment]
thanks, that'll fix it. will just decode it before we transmit it.
